//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KamilKielczewski.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KamilKielczewski.Resources.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use cookies to help our site work, to understand how it is used, and to tailor the adverts presented on our site. By clicking “Accept” below, you agree to us doing so..
        /// </summary>
        public static string Cookie {
            get {
                return ResourceManager.GetString("Cookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cute Dog.
        /// </summary>
        public static string CuteDog {
            get {
                return ResourceManager.GetString("CuteDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europa League.
        /// </summary>
        public static string EuropaLeague {
            get {
                return ResourceManager.GetString("EuropaLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Allowance.
        /// </summary>
        public static string FamilyAllowance {
            get {
                return ResourceManager.GetString("FamilyAllowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Górnik will face the Moldovan Zaria Balti. The host of the first match will be Zaria, who took the fifth place in the Moldavian first league. She got into the cups after retiring from the competition Dacia Kishinev..
        /// </summary>
        public static string firstNews1st {
            get {
                return ResourceManager.GetString("firstNews1st", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lech will play with Gandżasar Kapan from Armenia. The first match will take place on July 12 in Poznan in the empty stands (this is a penalty during the match of the last round of Lech - Legia Warsaw). Revision July 19..
        /// </summary>
        public static string firstNews2nd {
            get {
                return ResourceManager.GetString("firstNews2nd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the previous season, Gandzasar finished third in the Armenian Premier League and won the national cup..
        /// </summary>
        public static string firstNews3rd {
            get {
                return ResourceManager.GetString("firstNews3rd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The draw of the second round - then Jagiellonia Białystok, the runner-up of Poland, will enter the game - it will take place on Wednesday at 2:00 PM..
        /// </summary>
        public static string firstNews4th {
            get {
                return ResourceManager.GetString("firstNews4th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        public static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string languageText {
            get {
                return ResourceManager.GetString("languageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Page.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On May 15, the government approved changes in family benefits. It will grow, among others income criterion entitling to social assistance. The increase was forced by the protest of the guardians of people with disabilities in the Sejm..
        /// </summary>
        public static string secondNews1st {
            get {
                return ResourceManager.GetString("secondNews1st", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Council of Ministers accepted the proposal to change the amount of income criteria and amounts of benefits contained in the Act of 28 November 2003 on family benefits. As a result, more people will have a chance to receive benefits..
        /// </summary>
        public static string secondNews2nd {
            get {
                return ResourceManager.GetString("secondNews2nd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From 1 November 2018, some family benefits for disabled persons or their carers will increase.
        ///Care allowance will amount to PLN 184.42 (increase by PLN 31.42). Another raise of this allowance - up to PLN 215.84, will take effect from November 1, 2019.
        ///Special care allowance will be PLN 620 (increase by PLN 100).
        ///Guardian&apos;s allowance will increase to PLN 620 (by PLN 100)..
        /// </summary>
        public static string secondNews3rd {
            get {
                return ResourceManager.GetString("secondNews3rd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gas pipeline will run through Danish, Swedish and Polish waters. It will have 275 km..
        /// </summary>
        public static string thirdNews1st {
            get {
                return ResourceManager.GetString("thirdNews1st", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaz-System, responsible for the construction of the Baltic Pipe undersea pipeline, announced the selection of the preferred route for this investment..
        /// </summary>
        public static string thirdNews2nd {
            get {
                return ResourceManager.GetString("thirdNews2nd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The route will be run through Danish and Polish sea areas and the Swedish exclusive economic zone. Its length will be about 275 km. Earlier, Gaz-System reported that he was also considering German waters..
        /// </summary>
        public static string thirdNews3rd {
            get {
                return ResourceManager.GetString("thirdNews3rd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The starting point for the gas pipeline to land is Faxe South in Denmark (also considered Faxe North, in the same Faxe Bay) and Niechorze-Pogorzelica in Poland (also considered Rogowo and Gąski, located eastwards)..
        /// </summary>
        public static string thirdNews4th {
            get {
                return ResourceManager.GetString("thirdNews4th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All trademarks, logos and brands are property of their respective owners..
        /// </summary>
        public static string Trademark {
            get {
                return ResourceManager.GetString("Trademark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
